#!/bin/sh

path="/home/andrea/Documenti/Universita/SecondoSemestre/Note/"

cd "$HOME/Documenti/Universita/SecondoSemestre/Note/"

if [ -n "$WAYLAND_DISPLAY" ]; then
  file=$(rg --files --follow | bemenu --fn 'Hack 11' -p "wiki:" -i -l 20)
else
  file=$(rg --files --follow | grep "md" | rofi -dmenu -i -p "Wiki")
fi

[[ -n "$file" ]] || exit

completePath="$path$file"

exec alacritty -e nvim $completePath
# exec echo "$path/$file"
